openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /pinar/:
    get:
      operationId: pinar_list
      description: ''
      tags:
      - pinar
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Snippet'
          description: ''
    post:
      operationId: pinar_create
      description: ''
      tags:
      - pinar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Snippet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Snippet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Snippet'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snippet'
          description: ''
  /pinar{format}:
    get:
      operationId: pinar_formatted_list
      description: ''
      parameters:
      - in: path
        name: format
        schema:
          type: string
          enum:
          - .json
        required: true
      tags:
      - pinar
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Snippet'
          description: ''
    post:
      operationId: pinar_formatted_create
      description: ''
      parameters:
      - in: path
        name: format
        schema:
          type: string
          enum:
          - .json
        required: true
      tags:
      - pinar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Snippet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Snippet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Snippet'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snippet'
          description: ''
  /pinar/{id}/:
    get:
      operationId: pinar_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pinar
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snippet'
          description: ''
    put:
      operationId: pinar_update
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pinar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Snippet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Snippet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Snippet'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snippet'
          description: ''
    patch:
      operationId: pinar_partial_update
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pinar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSnippet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSnippet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSnippet'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snippet'
          description: ''
    delete:
      operationId: pinar_destroy
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pinar
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /pinar/{id}{format}:
    get:
      operationId: pinar_formatted_retrieve
      description: ''
      parameters:
      - in: path
        name: format
        schema:
          type: string
          enum:
          - .json
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pinar
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snippet'
          description: ''
    put:
      operationId: pinar_formatted_update
      description: ''
      parameters:
      - in: path
        name: format
        schema:
          type: string
          enum:
          - .json
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pinar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Snippet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Snippet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Snippet'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snippet'
          description: ''
    patch:
      operationId: pinar_formatted_partial_update
      description: ''
      parameters:
      - in: path
        name: format
        schema:
          type: string
          enum:
          - .json
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pinar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSnippet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSnippet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSnippet'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snippet'
          description: ''
    delete:
      operationId: pinar_formatted_destroy
      description: ''
      parameters:
      - in: path
        name: format
        schema:
          type: string
          enum:
          - .json
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pinar
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    LanguageEnum:
      enum:
      - abap
      - abnf
      - ada
      - adl
      - agda
      - aheui
      - ahk
      - alloy
      - ampl
      - antlr
      - antlr-as
      - antlr-cpp
      - antlr-csharp
      - antlr-java
      - antlr-objc
      - antlr-perl
      - antlr-python
      - antlr-ruby
      - apacheconf
      - apl
      - applescript
      - arduino
      - arrow
      - as
      - as3
      - aspectj
      - aspx-cs
      - aspx-vb
      - asy
      - at
      - augeas
      - autoit
      - awk
      - bare
      - basemake
      - bash
      - bat
      - bbcbasic
      - bbcode
      - bc
      - befunge
      - bib
      - blitzbasic
      - blitzmax
      - bnf
      - boa
      - boo
      - boogie
      - brainfuck
      - bst
      - bugs
      - c
      - c-objdump
      - ca65
      - cadl
      - camkes
      - capdl
      - capnp
      - cbmbas
      - ceylon
      - cfc
      - cfengine3
      - cfm
      - cfs
      - chai
      - chapel
      - charmci
      - cheetah
      - cirru
      - clay
      - clean
      - clojure
      - clojurescript
      - cmake
      - cobol
      - cobolfree
      - coffee-script
      - common-lisp
      - componentpascal
      - console
      - control
      - coq
      - cpp
      - cpp-objdump
      - cpsa
      - cr
      - crmsh
      - croc
      - cryptol
      - csharp
      - csound
      - csound-document
      - csound-score
      - css
      - css+django
      - css+erb
      - css+genshitext
      - css+lasso
      - css+mako
      - css+mozpreproc
      - css+myghty
      - css+php
      - css+smarty
      - cucumber
      - cuda
      - cypher
      - cython
      - d
      - d-objdump
      - dart
      - dasm16
      - delphi
      - devicetree
      - dg
      - diff
      - django
      - docker
      - doscon
      - dpatch
      - dtd
      - duel
      - dylan
      - dylan-console
      - dylan-lid
      - earl-grey
      - easytrieve
      - ebnf
      - ec
      - ecl
      - eiffel
      - elixir
      - elm
      - emacs
      - email
      - erb
      - erl
      - erlang
      - evoque
      - execline
      - extempore
      - ezhil
      - factor
      - fan
      - fancy
      - felix
      - fennel
      - fish
      - flatline
      - floscript
      - forth
      - fortran
      - fortranfixed
      - foxpro
      - freefem
      - fsharp
      - fstar
      - gap
      - gas
      - gdscript
      - genshi
      - genshitext
      - glsl
      - gnuplot
      - go
      - golo
      - gooddata-cl
      - gosu
      - groff
      - groovy
      - gst
      - haml
      - handlebars
      - haskell
      - haxeml
      - hexdump
      - hlsl
      - hsail
      - hspec
      - html
      - html+cheetah
      - html+django
      - html+evoque
      - html+genshi
      - html+handlebars
      - html+lasso
      - html+mako
      - html+myghty
      - html+ng2
      - html+php
      - html+smarty
      - html+twig
      - html+velocity
      - http
      - hx
      - hybris
      - hylang
      - i6t
      - icon
      - idl
      - idris
      - iex
      - igor
      - inform6
      - inform7
      - ini
      - io
      - ioke
      - irc
      - isabelle
      - j
      - jags
      - jasmin
      - java
      - javascript+mozpreproc
      - jcl
      - jlcon
      - js
      - js+cheetah
      - js+django
      - js+erb
      - js+genshitext
      - js+lasso
      - js+mako
      - js+myghty
      - js+php
      - js+smarty
      - jsgf
      - json
      - jsonld
      - jsp
      - julia
      - juttle
      - kal
      - kconfig
      - kmsg
      - koka
      - kotlin
      - lagda
      - lasso
      - lcry
      - lean
      - less
      - lhs
      - lidr
      - lighty
      - limbo
      - liquid
      - live-script
      - llvm
      - llvm-mir
      - llvm-mir-body
      - logos
      - logtalk
      - lsl
      - lua
      - make
      - mako
      - maql
      - mask
      - mason
      - mathematica
      - matlab
      - matlabsession
      - md
      - mime
      - minid
      - modelica
      - modula2
      - monkey
      - monte
      - moocode
      - moon
      - mosel
      - mozhashpreproc
      - mozpercentpreproc
      - mql
      - ms
      - mscgen
      - mupad
      - mxml
      - myghty
      - mysql
      - nasm
      - ncl
      - nemerle
      - nesc
      - newlisp
      - newspeak
      - ng2
      - nginx
      - nim
      - nit
      - nixos
      - notmuch
      - nsis
      - numpy
      - nusmv
      - objdump
      - objdump-nasm
      - objective-c
      - objective-c++
      - objective-j
      - ocaml
      - octave
      - odin
      - ooc
      - opa
      - openedge
      - pacmanconf
      - pan
      - parasail
      - pawn
      - peg
      - perl
      - perl6
      - php
      - pig
      - pike
      - pkgconfig
      - plpgsql
      - pointless
      - pony
      - postgresql
      - postscript
      - pot
      - pov
      - powershell
      - praat
      - prolog
      - promql
      - properties
      - protobuf
      - ps1con
      - psql
      - psysh
      - pug
      - puppet
      - py2tb
      - pycon
      - pypylog
      - pytb
      - python
      - python2
      - qbasic
      - qml
      - qvto
      - racket
      - ragel
      - ragel-c
      - ragel-cpp
      - ragel-d
      - ragel-em
      - ragel-java
      - ragel-objc
      - ragel-ruby
      - raw
      - rb
      - rbcon
      - rconsole
      - rd
      - reason
      - rebol
      - red
      - redcode
      - registry
      - resource
      - rexx
      - rhtml
      - ride
      - rnc
      - roboconf-graph
      - roboconf-instances
      - robotframework
      - rql
      - rsl
      - rst
      - rts
      - rust
      - sarl
      - sas
      - sass
      - sc
      - scala
      - scaml
      - scdoc
      - scheme
      - scilab
      - scss
      - sgf
      - shen
      - shexc
      - sieve
      - silver
      - singularity
      - slash
      - slim
      - slurm
      - smali
      - smalltalk
      - smarty
      - sml
      - snobol
      - snowball
      - solidity
      - sourceslist
      - sp
      - sparql
      - spec
      - splus
      - sql
      - sqlite3
      - squidconf
      - ssp
      - stan
      - stata
      - swift
      - swig
      - systemverilog
      - tads3
      - tap
      - tasm
      - tcl
      - tcsh
      - tcshcon
      - tea
      - termcap
      - terminfo
      - terraform
      - tex
      - text
      - thrift
      - tid
      - tnt
      - todotxt
      - toml
      - trac-wiki
      - treetop
      - ts
      - tsql
      - ttl
      - turtle
      - twig
      - typoscript
      - typoscriptcssdata
      - typoscripthtmldata
      - ucode
      - unicon
      - urbiscript
      - usd
      - vala
      - vb.net
      - vbscript
      - vcl
      - vclsnippets
      - vctreestatus
      - velocity
      - verilog
      - vgl
      - vhdl
      - vim
      - wdiff
      - webidl
      - whiley
      - x10
      - xml
      - xml+cheetah
      - xml+django
      - xml+erb
      - xml+evoque
      - xml+lasso
      - xml+mako
      - xml+myghty
      - xml+php
      - xml+smarty
      - xml+velocity
      - xorg.conf
      - xquery
      - xslt
      - xtend
      - xul+mozpreproc
      - yaml
      - yaml+jinja
      - yang
      - zeek
      - zephir
      - zig
      type: string
    PatchedSnippet:
      type: object
      properties:
        code:
          type: string
        title:
          type: string
          maxLength: 100
        language:
          $ref: '#/components/schemas/LanguageEnum'
    Snippet:
      type: object
      properties:
        code:
          type: string
        title:
          type: string
          maxLength: 100
        language:
          $ref: '#/components/schemas/LanguageEnum'
      required:
      - code
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: Session
